### ISSUE TITLE
Moving words to a database

### ISSUE THREAD

**Issue by bonnieli** [hatchways/team-iron-man#62]
Currently we store a bunch of words in an array (https://github.com/hatchways/team-iron-man/pull/52/files#diff-47f6a9121983e8cf61946f9ea544d38acf04834c68d5333fc1b5debb3cf61538R149) and then randomly pick the words

It's okay to keep these set words hard coded and a finite list, I would just move it away from the function so that it doesn't bloat up the GameEngine

**Comment by CSimbulan** [comment]
Yeah I was going to bring this up later on and give everyone else an opportunity to add their own words as well.
